dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- cd decide
- cp local_settings.travis.py local_settings.py
- python ./manage.py test --keepdb
deploy:
  provider: heroku
  app: articuno-census2
  strategy: git
  api_key:
    secure: S4cP0VcX6HBVEkt/z+I9PseOviGBFnl2MEDcUS6Clo3LaH7RAExV+2tbdABySaRJL3A/21PksA2Sbc5Y+9C3NaLM9hegUSWhOolp0uf8JcyyZ1WSJCKkcn/9zjUJHarUz1aJnRf/wToDyJpMEad7ep1RZmS4nxiMuCw7yJd0xbuFv0WHe0Rut230wr3PJ+7x6mDJMfCMfwKEHj+6SapzMecx/lf/os16Xg6qsKqfN7iZXTjCzJpxYVK+1eNYT3PvIp1/orN5p90zuxBbd3NNlwK7BSHap9j4YDPw9WOTbSQRyGB2ptS56o5h3JE40TXWlXhaNHB6/JbU3aTAIf6kq0yJ/WQ/O2DooG13mrfxsLnzHSLrdxZFgodyXJCXZ/Ui1ynJEAQvRkanYWLNDKBtL8H/bxhmDyWCSDJ2LQ16c0hUAlpLpruW1xXJN0jfS8nLRQpbRrt40zRYhzcH9czzhBs1HJ3UQi21dJ9nReO9GvgGvqt2xj1vjhMv0Ti8mamh4gwaZtBypOWj7i/2yc7d8hd/1mh5OWi5eq2Eu0qqGdNgudtjwD5CJIsw4YNVXNv+V/hg2dPZVNJvB1ITAP4aBDBWNzsD1iK85/83QPXLsJnmBl20dKfNiKFAZ2aHEFBswl6mMWRrEK1AzIiofZe+CvLeiEt9Mn/9fTV78t9dpUE=
