dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- cd decide
- cp travis_local_settings.py local_settings.py
- python ./manage.py test --keepdb
- rm local_settings.py
deploy:
  provider: heroku
  app: egc-articuno-census
  strategy: git
  on: articuno-census-deploy
  api_key:
    secure: JUSbuAb8ntTM0uvzd1ud6a9wWn7Exi94btWC+m8i/Xy/0Wqls+s0oMxJ8oCYf/EQpiDHR0ONqDIr0cVcU71cyH+MXFGsBcB0NxfGgeVGGrTZOfkgkyX2VZ4DCt7H2dIbJj0FKr1z1dcNQGQDaYdzOAetYgdmSmCrQq4eGnuGCrDbbraG2bRS8QeOFJpRhEzqf1+TLmwPn5kwgthNAOzgF/ng8XpVmgEdX+Jz2Du+/GNdPsRamIRoePxRSBqVrpF//Zn8MCQiJZnVIz3XM29VSGhBISdMMUvmwWn9bFy0ARxuUGDgq8ufwVDg1cSYwfWbklVzo9bsKLN5xtKShmBEohHw/rWjzdQctMNF1ZSatstWCWBuZ8pDwazAraLx5wCFe2YHLToHMZKwZRlTg2yF51ibebdo1X0NTu5W3vY3bSdPT6RHcCE8iJGLzf/QmWRo59SM0uezrWrATQpnByLMN8Wq8viP4USwU7HmqzX2kL0uNC5+mefi5HVdJ1X+yd7QZa0TIaOd2XEbexo6ozN5Fn2y+yBcBDXbNqxdK7G4o0bGkveS5w2dRDnlAxeZ3pUzeXbU2hjpOSH907ssBcSqAR2Qai5x5TsozkoPDxz9RAhvp5lavQgtoAIvjjNMF/VzCtuOc1I1Ju4u0+gAyZjgzPikgVo05t2bI7yhzjZ51Wk=
