dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- cd decide
- cp travis_local_settings.py local_settings.py
- python ./manage.py compilemessages
- python ./manage.py test --keepdb
- rm local_settings.py
deploy:
  skip_cleanup: true
  provider: heroku
  app: decide-articuno
  strategy: git
  on: articuno-booth-m4
  api_key:
    secure: sy0FnZjEUs8mzxamaeP2bvad1w2ZT0rp6N4zmvDbPOWpGEVxLxoZr2imO2QfEymrgwvinO3tQO40lrNOBb1vgR/KoJGbec0wfmP9r4xKPzL+vCGHetdWuBH6hkfQDELJXIzgDZ9x3jcuJ0eAXk2o7RJFPU7nGnLYaXu/T8DRxWTUcjiVBgvgfhyUnBqLcE9crT21OFsuP7nJADr68WHIh8PBulBbfcOfK6zjO+06PgZHDloE3SDHCrKelgCfEyJvImQjq+7IfNO/wsJe0tbGeiYmH6yzShlkggK02wxI4ao/673ijBL1qf+IyDQx3+sGiN+OnGfJ5BkbpPVxcFgbKKoMWp+akajKpXDoUVf+43CMS59D2GatDKfpQn5yDcGP0mwvBYTsmkadd+veMmDpQPDfB+BcoTcKtQ64OL1n5ygmH6pnW2pYa7yjZsF7HQ28eZ7FGosYX1nTCzdKC5Ii2xWSJxs9916EM9LFJvl/hB6Dtppp27XrIWGL42oBlMDSf1Tof3nyUmE/LR5nqFbJ6pFEizhYMtvsVYHJmfzoUfcJheWjTlFb8iIBWV2Arkiti+qf3J4CJV/JzH43VvEFLteTgMZbITrJElV6wp1G4vBKv8vJ2Kb1vz+eo/t66knCJ8vQCZ4XrZiTxx7PqGP/CKxNV8sPHWzoGM+qDc4Fa6s=
