dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- cd decide
- cp local_settings.travis.py local_settings.py
- python ./manage.py test --keepdb
deploy:
  provider: heroku
  app: articuno-census1
  strategy: git
      on: 
	branch: articuno-census-herok
  api_key:
    secure: T1h0VxvZxSGhcihFnkySbbBAF246RX866xpBWIWL+IQE7m3dZYX9XMRd4lF8B6ZsWlxKQ4LvetS1VK/evPAKV2M7AmFxtbT9bGsvszIODyF8jkBT9LYlN6EE/z671+RJE5kDKf0566dBPqbbWR2p/ETiB2+9bO1PmlM9AiOjhZ6RaJjKKb09DuSJN51LaXWX7hZ0l3WvsHl1Tz5JFHiB3YRdM/jNY9BXuWocF91zCbJ4fo7Ej/pqIz8NnQOze4o0Ih097Ah3eWPQOuRI3y51KhIiv/xyNhyHAHHMOBMDuaylYVAq0lDWLmMcIgSVCF4IbzQNox/sOFFKHoW672do2eIHLV65OXstnfU4YzVtAXt1XmNtNuz9pDCsnD05bZLGAgTtUYLHtgsLYOMMopxdMmCeOL71w35fwYhn6VWGn1Fx7njd0HkAISgmd3Cf5ZA+mOqdHegVxFc497fg+t4pg0btvXBwF+U3KgmVvJpb9YAUEu5a0WNwjPO7X1wWlvf4Y4+rjpz4vRyl2/DdpjdQFdgDPvjup4D7ehBiCDV2/OttLbYaLa/b9BJIhCWD8yEOK8CUgv7XXUF97G1GHcpjFFE0KvOATbOA0LgsJqKsraeOzFh2wc8sti8QyqZG+Y4sEftv5qrjZxVf8ewOWB0XB9vShcy8tz7JlTf71J8X3wo=
