dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- cd decide
- cp travis_local_settings.py local_settings.py
- python ./manage.py test --keepdb
- rm local_settings.py
deploy:
  provider: heroku
  app: articuno-postproc
  strategy: git
  on: postproc-deployment
  api_key:
    secure: PaaoiVbMMZbB+i0kb1lBdUHYmuDeLykmB4r7IAlNiNH7ssr/RRdytBsCo+X84npcyrykx7VLMD+khrhqkVduFaTnMMFvvBNKxuuDU9BVhR5Yi0SqWvJRio6uR/6JucI6X24lUOwr8LAoIKEGHyrcxIruiaXL8wE9cdvAMFnCn/eCrIyJ/OVx+KKr6qIYc7+Wc5r1MKbtIDNa/EkVWq8vJqrs0kLrjyBpKUlbqO8YWEf/jOyXYVG0MxGOuAQgRnTHoQryCaHwjLu66JTkjk8YBOdySLdyjpMmkyUE025bjWqi9Utnjn1QgUH4cWN4PSQG2a9da9MH+2YzeRHdt6ltfzZffxRjdFBOO2iTwiFWkljFUls8q03rNuYaMHb3vCOjFJ3epZmMvplko6xKR5CptjAHkmnuk0EZ43JoSwY135t/azTa/BjAYZBPLdLKbZ7bUwXfo7JWVniAqBVqtaMnfbVS3tmGsIToHMIBZcq4worCRnVf/+Hpj1USvvCmgGGce4Za/VpNJi3/JavWviDOGKFYCydjXqZBuZ2wJPpSp7nB2gJOBZmIG97CzFuOtRBol3XWfWJA9tetZD0jW7avwDVPI7Nda+nQwM4sE59UvctKN0RY0YPK2ZdTUs3QntU72BUSVrNHuxUU9g8O8/8rB8VvHQrJcDWfRlqNNORSOUE=
