dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- cd decide
- cp travis_local_settings.py local_settings.py
- python ./manage.py compilemessages
- python ./manage.py test --keepdb
- rm local_settings.py
deploy:
  skip_cleanup: true
  provider: heroku
  app: decide-articuno
  strategy: git
  on: articuno-booth-m4
  api_key:
    secure: lfBQmJDvqRATCKy0uxKpIgCgMzS6mg5Wq/8/eMsprt0f0D/L3t3ECTILvTtqawSwmD+/qFAc2t/qU9c+Ld7S6z/1cBaC9tHRRI79uA31zTw25VWenaxpTx7JuSo0CpKn7RTxH+gYwpYyXtJNxqJV9baztAkmCEzdDoZcimAPNzXXLVF4sHzUjA2C10nRP8G+6cSgImQS0R5ffKgiKZK/tIyEzIwjdrk4DSwQ4LBLDksppiOv7qRL/1y2Ab6/OikOyYyTw24KTxKiwyc3JQs9Qj0OR8OsLkqEesniz3ypsZe64dUazbEH6YguqvSCamcS0pKGxjsefWvJ3k0yn44uW8sGvEST4cCPoFmvltPof4WBDwNUDCnJ3YNi0LzSnyKdvQ3LPxuhL7xfR8OJM5diTOp+nCqIcBfU/YyMA16z8dcARiHXY5lcqdFZiijzIZ2xOD3ifnXReney8vnshvSGa9nyzCtqaKOUofZDFxmw0+aBmHw4VOuGXbr/72945xXUxdOK/YXk4oTFAEXJXjWtkWEd+5tXh8qqQbA5xyLhcnndRQKPb1SjZAq3Mm34dLJB1gRyUGuKlEy4XJaNOzWvgEbjmCs6+8HieJopUtiR8mfTABcvDqExwW4yGhnj8vDdRvP6qsqx8qaoSjKXCBa41Jdg4QN0jX58I1ti/sFnO+I=
