# Generated by Django 2.0 on 2019-12-04 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20180605_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyCongressCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('congress_candidate', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PartyPresidentCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('president_candidate', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PoliticalParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='questionoption',
            name='question',
        ),
        migrations.RemoveField(
            model_name='voting',
            name='question',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionOption',
        ),
        migrations.AddField(
            model_name='partypresidentcandidate',
            name='politicalParty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='president_candidates', to='voting.PoliticalParty'),
        ),
        migrations.AddField(
            model_name='partycongresscandidate',
            name='politicalParty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='congress_candidates', to='voting.PoliticalParty'),
        ),
        migrations.AddField(
            model_name='voting',
            name='party',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='voting', to='voting.PoliticalParty'),
            preserve_default=False,
        ),
    ]
