# Generated by Django 2.0 on 2019-12-04 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_auto_20191204_0615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='party',
        ),
        migrations.AddField(
            model_name='politicalparty',
            name='voting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='party', to='voting.Voting'),
            preserve_default=False,
        ),
    ]
