# Generated by Django 2.0 on 2019-12-04 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_auto_20191204_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicalparty',
            name='voting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='voting.Voting'),
        ),
    ]
