# Generated by Django 2.0 on 2019-12-04 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_auto_20191204_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='partycongresscandidate',
            name='gender',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], default='H', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partycongresscandidate',
            name='postal_code',
            field=models.PositiveIntegerField(default=41440, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partypresidentcandidate',
            name='gender',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], default='H', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partypresidentcandidate',
            name='postal_code',
            field=models.PositiveIntegerField(default=41440, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(5)]),
            preserve_default=False,
        ),
    ]
