# Generated by Django 2.0 on 2019-12-04 09:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_auto_20191204_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partycongresscandidate',
            name='postal_code',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='partypresidentcandidate',
            name='postal_code',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
