# Generated by Django 2.0 on 2019-12-04 09:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_auto_20191204_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partycongresscandidate',
            name='postal_code',
            field=models.PositiveIntegerField(validators=[django.core.validators.RegexValidator('^\\d[0-9]{5}$')]),
        ),
        migrations.AlterField(
            model_name='partypresidentcandidate',
            name='postal_code',
            field=models.PositiveIntegerField(validators=[django.core.validators.RegexValidator('^\\d[0-9]{5}$')]),
        ),
    ]
