# Generated by Django 2.0 on 2020-01-07 12:19

import django.core.validators
from django.db import migrations, models
import voting.models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0013_voting_blank_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partycongresscandidate',
            name='postal_code',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^[0-9]{5}$'), voting.models.PartyCongressCandidate.valid]),
        ),
        migrations.AlterField(
            model_name='partypresidentcandidate',
            name='postal_code',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^[0-9]{5}$'), voting.models.PartyPresidentCandidate.valid]),
        ),
    ]
