# Generated by Django 2.0 on 2020-01-11 20:49

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200109_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='postal_code',
            field=models.IntegerField(validators=[authentication.models.validate_postal_code]),
        ),
    ]
