# Generated by Django 2.0 on 2020-01-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20200111_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='postal_code',
            field=models.IntegerField(),
        ),
    ]
