# Generated by Django 2.0 on 2020-01-07 11:57

import base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20180921_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cipher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', base.models.BigBigField()),
                ('b', base.models.BigBigField()),
            ],
        ),
        migrations.RemoveField(
            model_name='vote',
            name='a',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='b',
        ),
        migrations.AddField(
            model_name='cipher',
            name='vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciphers', to='store.Vote'),
        ),
    ]
